alter table "public"."Mentor" drop constraint "Mentor_organiztionId_fkey";

alter table "public"."MonthGroup" drop constraint "MonthGroup_organizationId_fkey";

alter table "public"."Organiztion" drop constraint "Organiztion_id_key";

alter table "public"."TimeRestriction" drop constraint "TimeRestriction_id_key";

alter table "public"."TimeRestriction" drop constraint "TimeRestriction_organizationId_fkey";

alter table "public"."Group" drop constraint "Group_organizationId_fkey";

alter table "public"."MonthGroup" drop constraint "MonthGroup_pkey";

alter table "public"."Organiztion" drop constraint "Organiztion_pkey";

alter table "public"."TimeRestriction" drop constraint "TimeRestriction_pkey";

drop index if exists "public"."MonthGroup_pkey";

drop index if exists "public"."TimeRestriction_id_key";

drop index if exists "public"."TimeRestriction_pkey";

drop index if exists "public"."Organiztion_id_key";

drop index if exists "public"."Organiztion_pkey";

drop table "public"."MonthGroup";

drop table "public"."Organiztion";

drop table "public"."TimeRestriction";

create table "public"."Attend" (
    "id" bigint generated by default as identity not null,
    "childName" text,
    "date" date,
    "attend" text,
    "groupId" character varying not null,
    "childId" bigint,
    "organizationId" bigint
);


create table "public"."Organization" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "secretCode" double precision
);


alter table "public"."Group" drop column "children";

alter table "public"."Group" add column "groupId" character varying not null;

alter table "public"."Mentor" drop column "name";

alter table "public"."Mentor" drop column "organiztionId";

alter table "public"."Mentor" add column "fullName" text;

alter table "public"."Mentor" add column "login" text;

alter table "public"."Mentor" add column "organizationId" bigint;

alter table "public"."Mentor" add column "password" text;

CREATE UNIQUE INDEX "Attend_id_key" ON public."Attend" USING btree (id);

CREATE UNIQUE INDEX "Attend_pkey" ON public."Attend" USING btree (id);

CREATE UNIQUE INDEX "Mentor_login_key" ON public."Mentor" USING btree (login);

CREATE UNIQUE INDEX "Organization_passCode_key" ON public."Organization" USING btree ("secretCode");

CREATE UNIQUE INDEX "Organiztion_id_key" ON public."Organization" USING btree (id);

CREATE UNIQUE INDEX "Organiztion_pkey" ON public."Organization" USING btree (id);

alter table "public"."Attend" add constraint "Attend_pkey" PRIMARY KEY using index "Attend_pkey";

alter table "public"."Organization" add constraint "Organiztion_pkey" PRIMARY KEY using index "Organiztion_pkey";

alter table "public"."Attend" add constraint "Attend_id_key" UNIQUE using index "Attend_id_key";

alter table "public"."Mentor" add constraint "Mentor_login_key" UNIQUE using index "Mentor_login_key";

alter table "public"."Mentor" add constraint "Mentor_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"(id) not valid;

alter table "public"."Mentor" validate constraint "Mentor_organizationId_fkey";

alter table "public"."Organization" add constraint "Organization_passCode_key" UNIQUE using index "Organization_passCode_key";

alter table "public"."Organization" add constraint "Organiztion_id_key" UNIQUE using index "Organiztion_id_key";

alter table "public"."Group" add constraint "Group_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"(id) not valid;

alter table "public"."Group" validate constraint "Group_organizationId_fkey";


