alter table "public"."page" drop constraint "page_parent_page_id_fkey";

alter table "public"."page" drop constraint "page_path_key";

alter table "public"."page_section" drop constraint "page_section_page_id_fkey";

drop function if exists "public"."get_page_parents"(page_id bigint);

drop function if exists "public"."match_page_sections"(embedding vector, match_threshold double precision, match_count integer, min_content_length integer);

drop function if exists "public"."match_page_sections_v2"(embedding vector, match_threshold double precision, min_content_length integer);

alter table "public"."page" drop constraint "page_pkey";

alter table "public"."page_section" drop constraint "page_section_pkey";

drop index if exists "public"."page_path_key";

drop index if exists "public"."page_pkey";

drop index if exists "public"."page_section_pkey";

drop table "public"."page";

drop table "public"."page_section";

create table "public"."Group" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "organizationId" bigint not null,
    "children" jsonb
);


create table "public"."Mentor" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "organiztionId" bigint,
    "groupId" bigint
);


create table "public"."MonthGroup" (
    "id" bigint generated by default as identity not null,
    "month" smallint not null default '1'::smallint,
    "name" text,
    "organizationId" bigint not null,
    "children" jsonb
);


create table "public"."Organiztion" (
    "id" bigint generated by default as identity not null,
    "name" text
);


alter table "public"."Organiztion" enable row level security;

create table "public"."TimeRestriction" (
    "id" bigint generated by default as identity not null,
    "organizationId" bigint,
    "timeStart" time without time zone,
    "timeEnd" time without time zone
);


create table "public"."schema_migrations" (
    "version" character varying(128) not null
);


drop sequence if exists "public"."page_id_seq";

drop sequence if exists "public"."page_section_id_seq";

drop extension if exists "vector";

CREATE UNIQUE INDEX "Group_pkey" ON public."Group" USING btree (id);

CREATE UNIQUE INDEX "Mentor_id_key" ON public."Mentor" USING btree (id);

CREATE UNIQUE INDEX "Mentor_pkey" ON public."Mentor" USING btree (id);

CREATE UNIQUE INDEX "MonthGroup_pkey" ON public."MonthGroup" USING btree (id);

CREATE UNIQUE INDEX "Organiztion_id_key" ON public."Organiztion" USING btree (id);

CREATE UNIQUE INDEX "Organiztion_pkey" ON public."Organiztion" USING btree (id);

CREATE UNIQUE INDEX "TimeRestriction_id_key" ON public."TimeRestriction" USING btree (id);

CREATE UNIQUE INDEX "TimeRestriction_pkey" ON public."TimeRestriction" USING btree (id);

CREATE UNIQUE INDEX schema_migrations_pkey ON public.schema_migrations USING btree (version);

alter table "public"."Group" add constraint "Group_pkey" PRIMARY KEY using index "Group_pkey";

alter table "public"."Mentor" add constraint "Mentor_pkey" PRIMARY KEY using index "Mentor_pkey";

alter table "public"."MonthGroup" add constraint "MonthGroup_pkey" PRIMARY KEY using index "MonthGroup_pkey";

alter table "public"."Organiztion" add constraint "Organiztion_pkey" PRIMARY KEY using index "Organiztion_pkey";

alter table "public"."TimeRestriction" add constraint "TimeRestriction_pkey" PRIMARY KEY using index "TimeRestriction_pkey";

alter table "public"."schema_migrations" add constraint "schema_migrations_pkey" PRIMARY KEY using index "schema_migrations_pkey";

alter table "public"."Group" add constraint "Group_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organiztion"(id) not valid;

alter table "public"."Group" validate constraint "Group_organizationId_fkey";

alter table "public"."Mentor" add constraint "Mentor_id_key" UNIQUE using index "Mentor_id_key";

alter table "public"."Mentor" add constraint "Mentor_organiztionId_fkey" FOREIGN KEY ("organiztionId") REFERENCES "Organiztion"(id) not valid;

alter table "public"."Mentor" validate constraint "Mentor_organiztionId_fkey";

alter table "public"."MonthGroup" add constraint "MonthGroup_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organiztion"(id) not valid;

alter table "public"."MonthGroup" validate constraint "MonthGroup_organizationId_fkey";

alter table "public"."Organiztion" add constraint "Organiztion_id_key" UNIQUE using index "Organiztion_id_key";

alter table "public"."TimeRestriction" add constraint "TimeRestriction_id_key" UNIQUE using index "TimeRestriction_id_key";

alter table "public"."TimeRestriction" add constraint "TimeRestriction_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organiztion"(id) not valid;

alter table "public"."TimeRestriction" validate constraint "TimeRestriction_organizationId_fkey";


